"""agregar activo a las tablas rol  y user

Revision ID: a5d5711a9eac
Revises: f7f9e1806741
Create Date: 2026-03-31 22:20:35.476825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5d5711a9eac'
down_revision = 'f7f9e1806741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.String(length=1), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.String(length=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('activo')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
